# this is sample
repository: Undecided/Oshavery-Server
url: http://localhost
port: 3080
secretKeyFilePath: ".config/oshavery-config.yaml"
publicKeyFilePath: ".config/oshavery-config.yaml"
allowRegister: true
storage:
  keyFile: /oshavery/keyfile.json
  bucketName: test
  mediaServerURL: localhost
